export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const PROFILE_USER_FAIL = 'PROFILE_USER_FAIL'
export const PROFILE_USER_SUCCESS = 'PROFILE_USER_SUCCESS'
export const PROFILE_USER = 'PROFILE_USER'

// update profile
export const PROFILE_USER_UPDATE = 'PROFILE_USER_UPDATE'
export const PROFILE_USER_UPDATE_SUCESS = 'PROFILE_USER_UPDATE_SUCESS'
export const PROFILE_USER_UPDATE_FAIL = 'PROFILE_USER_UPDATE_FAIL'
